// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// AI inference — stub when ai feature not enabled
Future<Float32List> runInference(
        {required String modelPath,
        required List<int> inputPixels,
        required int width,
        required int height}) =>
    RustLib.instance.api.crateApiAiRunInference(
        modelPath: modelPath,
        inputPixels: inputPixels,
        width: width,
        height: height);
