// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Apply basic edits to image pixels (exposure, contrast, etc.)
/// Input: RGBA pixel data, Output: edited RGBA pixel data
Future<Uint8List> applyEdits(
        {required List<int> pixels,
        required int width,
        required int height,
        required EditParams params}) =>
    RustLib.instance.api.crateApiEditingApplyEdits(
        pixels: pixels, width: width, height: height, params: params);

/// Generate a histogram from RGBA pixel data
Future<HistogramResult> computeHistogram({required List<int> pixels}) =>
    RustLib.instance.api.crateApiEditingComputeHistogram(pixels: pixels);

class EditParams {
  final double exposure;
  final double contrast;
  final double highlights;
  final double shadows;
  final double whites;
  final double blacks;
  final double temperature;
  final double tint;
  final double vibrance;
  final double saturation;
  final double clarity;
  final double texture;
  final double dehaze;

  const EditParams({
    required this.exposure,
    required this.contrast,
    required this.highlights,
    required this.shadows,
    required this.whites,
    required this.blacks,
    required this.temperature,
    required this.tint,
    required this.vibrance,
    required this.saturation,
    required this.clarity,
    required this.texture,
    required this.dehaze,
  });

  static Future<EditParams> default_() =>
      RustLib.instance.api.crateApiEditingEditParamsDefault();

  @override
  int get hashCode =>
      exposure.hashCode ^
      contrast.hashCode ^
      highlights.hashCode ^
      shadows.hashCode ^
      whites.hashCode ^
      blacks.hashCode ^
      temperature.hashCode ^
      tint.hashCode ^
      vibrance.hashCode ^
      saturation.hashCode ^
      clarity.hashCode ^
      texture.hashCode ^
      dehaze.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditParams &&
          runtimeType == other.runtimeType &&
          exposure == other.exposure &&
          contrast == other.contrast &&
          highlights == other.highlights &&
          shadows == other.shadows &&
          whites == other.whites &&
          blacks == other.blacks &&
          temperature == other.temperature &&
          tint == other.tint &&
          vibrance == other.vibrance &&
          saturation == other.saturation &&
          clarity == other.clarity &&
          texture == other.texture &&
          dehaze == other.dehaze;
}

class HistogramResult {
  final Int32List red;
  final Int32List green;
  final Int32List blue;
  final Int32List luminance;

  const HistogramResult({
    required this.red,
    required this.green,
    required this.blue,
    required this.luminance,
  });

  @override
  int get hashCode =>
      red.hashCode ^ green.hashCode ^ blue.hashCode ^ luminance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistogramResult &&
          runtimeType == other.runtimeType &&
          red == other.red &&
          green == other.green &&
          blue == other.blue &&
          luminance == other.luminance;
}
