// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Export an image to a specific format
Future<void> exportImage(
        {required List<int> pixels,
        required int width,
        required int height,
        required String outputPath,
        required String format,
        required int quality}) =>
    RustLib.instance.api.crateApiExportExportImage(
        pixels: pixels,
        width: width,
        height: height,
        outputPath: outputPath,
        format: format,
        quality: quality);
