// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Decode a photo file (RAW or standard) into RGBA pixel data
Future<DecodedImageWrapper> decodePhoto({required String path}) =>
    RustLib.instance.api.crateApiPhotoDecodingDecodePhoto(path: path);

/// Decode a photo at reduced resolution for thumbnails/previews
Future<DecodedImageWrapper> decodePhotoPreview(
        {required String path, required int maxSize}) =>
    RustLib.instance.api
        .crateApiPhotoDecodingDecodePhotoPreview(path: path, maxSize: maxSize);

/// Extract EXIF metadata from a photo file
Future<RawMetadataResponse> extractMetadata({required String path}) =>
    RustLib.instance.api.crateApiPhotoDecodingExtractMetadata(path: path);

/// Check if a file is a supported RAW format
Future<bool> isRawFile({required String path}) =>
    RustLib.instance.api.crateApiPhotoDecodingIsRawFile(path: path);

/// Get list of supported RAW file extensions
Future<List<String>> supportedRawExtensions() =>
    RustLib.instance.api.crateApiPhotoDecodingSupportedRawExtensions();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DecodedImageWrapper>>
abstract class DecodedImageWrapper implements RustOpaqueInterface {
  DecodedImage get inner;

  set inner(DecodedImage inner);

  Future<Uint8List> data();

  Future<int> height();

  Future<int> width();
}

class DecodedImage {
  final int width;
  final int height;
  final Uint8List data;

  const DecodedImage({
    required this.width,
    required this.height,
    required this.data,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedImage &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          data == other.data;
}

class RawMetadataResponse {
  final int width;
  final int height;
  final String format;
  final String? cameraMake;
  final String? cameraModel;
  final String? lens;
  final int? iso;
  final double? aperture;
  final String? shutterSpeed;
  final double? focalLength;
  final String? captureDate;
  final int? orientation;
  final int? bitDepth;

  const RawMetadataResponse({
    required this.width,
    required this.height,
    required this.format,
    this.cameraMake,
    this.cameraModel,
    this.lens,
    this.iso,
    this.aperture,
    this.shutterSpeed,
    this.focalLength,
    this.captureDate,
    this.orientation,
    this.bitDepth,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      format.hashCode ^
      cameraMake.hashCode ^
      cameraModel.hashCode ^
      lens.hashCode ^
      iso.hashCode ^
      aperture.hashCode ^
      shutterSpeed.hashCode ^
      focalLength.hashCode ^
      captureDate.hashCode ^
      orientation.hashCode ^
      bitDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawMetadataResponse &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          format == other.format &&
          cameraMake == other.cameraMake &&
          cameraModel == other.cameraModel &&
          lens == other.lens &&
          iso == other.iso &&
          aperture == other.aperture &&
          shutterSpeed == other.shutterSpeed &&
          focalLength == other.focalLength &&
          captureDate == other.captureDate &&
          orientation == other.orientation &&
          bitDepth == other.bitDepth;
}
