import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );

    // Auth: must be admin
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: corsHeaders });

    const { data: { user }, error: authError } = await supabase.auth.getUser(authHeader.replace('Bearer ', ''));
    if (authError || !user) return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: corsHeaders });

    // Only admins and super_admins can generate invite links
    const { data: profile } = await supabase.from('user_profiles').select('role').eq('id', user.id).single();
    if (!profile || !['admin', 'super_admin'].includes(profile.role)) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), { status: 403, headers: corsHeaders });
    }

    const body = await req.json().catch(() => ({}));
    const { client_id, label, expires_in_days } = body;

    // Generate expiry (default: never)
    const expiresAt = expires_in_days
      ? new Date(Date.now() + expires_in_days * 86400000).toISOString()
      : null;

    // Insert invite record — token auto-generated by DB default
    const { data: invite, error: insertError } = await supabase
      .from('client_invite_links')
      .insert({
        admin_id: user.id,
        client_id: client_id || null,
        label: label || null,
        expires_at: expiresAt,
      })
      .select()
      .single();

    if (insertError) throw insertError;

    // Get platform settings for app download links and app name
    const { data: settings } = await supabase
      .from('platform_settings')
      .select('key, value')
      .in('key', ['platform_app_android_link', 'platform_app_ios_link', 'platform_app_name']);

    const settingsMap: Record<string, string> = {};
    (settings || []).forEach((s: any) => { settingsMap[s.key] = s.value || ''; });

    const appName = settingsMap['platform_app_name'] || 'Epix Visuals';
    const androidLink = settingsMap['platform_app_android_link'] || 'https://play.google.com/store';
    const iosLink = settingsMap['platform_app_ios_link'] || 'https://apps.apple.com';

    // Get the photographer's unique code (for the client to identify themselves as his client)
    const { data: photographerProfile } = await supabase
      .from('user_profiles')
      .select('photographer_code, name')
      .eq('id', user.id)
      .single();

    const photographerCode = photographerProfile?.photographer_code || null;
    const photographerName = photographerProfile?.name || 'Your photographer';

    // Build the universal invite URL
    // Format: <app_deep_link>?ref=<admin_id>&invite=<token>
    // This URL is used in sharing — when the user opens it on their device:
    //  - If app is installed → deep link opens the app which reads the params
    //  - If app not installed → fallback to app store
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const projectRef = supabaseUrl.replace('https://', '').split('.')[0];

    // The deep link scheme — matches expo-linking config
    // epixvisuals://join?ref=ADMIN_ID&invite=TOKEN
    const deepLink = `epixvisuals://join?ref=${user.id}&invite=${invite.token}`;

    // Universal fallback URL (for SMS/WhatsApp sharing — opens web which redirects)
    const webFallback = `https://${projectRef}.supabase.co/functions/v1/invite_redirect?ref=${user.id}&invite=${invite.token}`;

    return new Response(JSON.stringify({
      success: true,
      token: invite.token,
      admin_id: user.id,
      deep_link: deepLink,
      web_fallback: webFallback,
      android_link: androidLink,
      ios_link: iosLink,
      app_name: appName,
      photographer_code: photographerCode,
      // Full share message ready to paste into SMS/WhatsApp
      // Includes the photographer's unique code so the client is identified as theirs
      share_message: [
        `Hi! ${photographerName} is sharing your photo gallery via ${appName}.`,
        ``,
        `📲 Download the app to view your photos:`,
        `🤖 Android: ${androidLink}`,
        `🍎 iOS: ${iosLink}`,
        ``,
        photographerCode
          ? `🔑 Photographer code: *${photographerCode}*\n   (Enter this in the app to connect to ${photographerName})`
          : null,
        ``,
        `🔗 Or tap this link to connect automatically:\n${webFallback}`,
      ].filter(line => line !== null).join('\n'),
      expires_at: invite.expires_at,
      created_at: invite.created_at,
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error: any) {
    console.error('generate_invite_link error:', error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
