// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ai.dart';
import 'api/editing.dart';
import 'api/export.dart';
import 'api/photo_decoding.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -383369797;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'photo_access_bridge',
    ioDirectory: '../../services/photo_access_bridge/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  DecodedImage crateApiPhotoDecodingDecodedImageWrapperAutoAccessorGetInner(
      {required DecodedImageWrapper that});

  void crateApiPhotoDecodingDecodedImageWrapperAutoAccessorSetInner(
      {required DecodedImageWrapper that, required DecodedImage inner});

  Future<Uint8List> crateApiPhotoDecodingDecodedImageWrapperData(
      {required DecodedImageWrapper that});

  Future<int> crateApiPhotoDecodingDecodedImageWrapperHeight(
      {required DecodedImageWrapper that});

  Future<int> crateApiPhotoDecodingDecodedImageWrapperWidth(
      {required DecodedImageWrapper that});

  Future<Uint8List> crateApiEditingApplyEdits(
      {required List<int> pixels,
      required int width,
      required int height,
      required EditParams params});

  Future<HistogramResult> crateApiEditingComputeHistogram(
      {required List<int> pixels});

  Future<DecodedImageWrapper> crateApiPhotoDecodingDecodePhoto(
      {required String path});

  Future<DecodedImageWrapper> crateApiPhotoDecodingDecodePhotoPreview(
      {required String path, required int maxSize});

  Future<EditParams> crateApiEditingEditParamsDefault();

  Future<void> crateApiExportExportImage(
      {required List<int> pixels,
      required int width,
      required int height,
      required String outputPath,
      required String format,
      required int quality});

  Future<RawMetadataResponse> crateApiPhotoDecodingExtractMetadata(
      {required String path});

  Future<bool> crateApiPhotoDecodingIsRawFile({required String path});

  Future<Float32List> crateApiAiRunInference(
      {required String modelPath,
      required List<int> inputPixels,
      required int width,
      required int height});

  Future<List<String>> crateApiPhotoDecodingSupportedRawExtensions();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_DecodedImageWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_DecodedImageWrapper;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_DecodedImageWrapperPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  DecodedImage crateApiPhotoDecodingDecodedImageWrapperAutoAccessorGetInner(
      {required DecodedImageWrapper that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_decoded_image,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiPhotoDecodingDecodedImageWrapperAutoAccessorGetInnerConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiPhotoDecodingDecodedImageWrapperAutoAccessorGetInnerConstMeta =>
          const TaskConstMeta(
            debugName: "DecodedImageWrapper_auto_accessor_get_inner",
            argNames: ["that"],
          );

  @override
  void crateApiPhotoDecodingDecodedImageWrapperAutoAccessorSetInner(
      {required DecodedImageWrapper that, required DecodedImage inner}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
            that, serializer);
        sse_encode_decoded_image(inner, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiPhotoDecodingDecodedImageWrapperAutoAccessorSetInnerConstMeta,
      argValues: [that, inner],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiPhotoDecodingDecodedImageWrapperAutoAccessorSetInnerConstMeta =>
          const TaskConstMeta(
            debugName: "DecodedImageWrapper_auto_accessor_set_inner",
            argNames: ["that", "inner"],
          );

  @override
  Future<Uint8List> crateApiPhotoDecodingDecodedImageWrapperData(
      {required DecodedImageWrapper that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPhotoDecodingDecodedImageWrapperDataConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingDecodedImageWrapperDataConstMeta =>
      const TaskConstMeta(
        debugName: "DecodedImageWrapper_data",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiPhotoDecodingDecodedImageWrapperHeight(
      {required DecodedImageWrapper that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPhotoDecodingDecodedImageWrapperHeightConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingDecodedImageWrapperHeightConstMeta =>
      const TaskConstMeta(
        debugName: "DecodedImageWrapper_height",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiPhotoDecodingDecodedImageWrapperWidth(
      {required DecodedImageWrapper that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPhotoDecodingDecodedImageWrapperWidthConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingDecodedImageWrapperWidthConstMeta =>
      const TaskConstMeta(
        debugName: "DecodedImageWrapper_width",
        argNames: ["that"],
      );

  @override
  Future<Uint8List> crateApiEditingApplyEdits(
      {required List<int> pixels,
      required int width,
      required int height,
      required EditParams params}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pixels, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        sse_encode_box_autoadd_edit_params(params, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEditingApplyEditsConstMeta,
      argValues: [pixels, width, height, params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEditingApplyEditsConstMeta => const TaskConstMeta(
        debugName: "apply_edits",
        argNames: ["pixels", "width", "height", "params"],
      );

  @override
  Future<HistogramResult> crateApiEditingComputeHistogram(
      {required List<int> pixels}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pixels, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_histogram_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEditingComputeHistogramConstMeta,
      argValues: [pixels],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEditingComputeHistogramConstMeta =>
      const TaskConstMeta(
        debugName: "compute_histogram",
        argNames: ["pixels"],
      );

  @override
  Future<DecodedImageWrapper> crateApiPhotoDecodingDecodePhoto(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPhotoDecodingDecodePhotoConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingDecodePhotoConstMeta =>
      const TaskConstMeta(
        debugName: "decode_photo",
        argNames: ["path"],
      );

  @override
  Future<DecodedImageWrapper> crateApiPhotoDecodingDecodePhotoPreview(
      {required String path, required int maxSize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_u_32(maxSize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPhotoDecodingDecodePhotoPreviewConstMeta,
      argValues: [path, maxSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingDecodePhotoPreviewConstMeta =>
      const TaskConstMeta(
        debugName: "decode_photo_preview",
        argNames: ["path", "maxSize"],
      );

  @override
  Future<EditParams> crateApiEditingEditParamsDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_edit_params,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiEditingEditParamsDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEditingEditParamsDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "edit_params_default",
        argNames: [],
      );

  @override
  Future<void> crateApiExportExportImage(
      {required List<int> pixels,
      required int width,
      required int height,
      required String outputPath,
      required String format,
      required int quality}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pixels, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_String(format, serializer);
        sse_encode_u_32(quality, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiExportExportImageConstMeta,
      argValues: [pixels, width, height, outputPath, format, quality],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiExportExportImageConstMeta => const TaskConstMeta(
        debugName: "export_image",
        argNames: [
          "pixels",
          "width",
          "height",
          "outputPath",
          "format",
          "quality"
        ],
      );

  @override
  Future<RawMetadataResponse> crateApiPhotoDecodingExtractMetadata(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_raw_metadata_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPhotoDecodingExtractMetadataConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingExtractMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "extract_metadata",
        argNames: ["path"],
      );

  @override
  Future<bool> crateApiPhotoDecodingIsRawFile({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPhotoDecodingIsRawFileConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingIsRawFileConstMeta =>
      const TaskConstMeta(
        debugName: "is_raw_file",
        argNames: ["path"],
      );

  @override
  Future<Float32List> crateApiAiRunInference(
      {required String modelPath,
      required List<int> inputPixels,
      required int width,
      required int height}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(modelPath, serializer);
        sse_encode_list_prim_u_8_loose(inputPixels, serializer);
        sse_encode_u_32(width, serializer);
        sse_encode_u_32(height, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_f_32_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiAiRunInferenceConstMeta,
      argValues: [modelPath, inputPixels, width, height],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAiRunInferenceConstMeta => const TaskConstMeta(
        debugName: "run_inference",
        argNames: ["modelPath", "inputPixels", "width", "height"],
      );

  @override
  Future<List<String>> crateApiPhotoDecodingSupportedRawExtensions() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPhotoDecodingSupportedRawExtensionsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPhotoDecodingSupportedRawExtensionsConstMeta =>
      const TaskConstMeta(
        debugName: "supported_raw_extensions",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_DecodedImageWrapper => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_DecodedImageWrapper => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DecodedImageWrapper
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DecodedImageWrapper
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DecodedImageWrapper
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DecodedImageWrapper
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EditParams dco_decode_box_autoadd_edit_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_edit_params(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DecodedImage dco_decode_decoded_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DecodedImage(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      data: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  EditParams dco_decode_edit_params(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return EditParams(
      exposure: dco_decode_f_64(arr[0]),
      contrast: dco_decode_f_64(arr[1]),
      highlights: dco_decode_f_64(arr[2]),
      shadows: dco_decode_f_64(arr[3]),
      whites: dco_decode_f_64(arr[4]),
      blacks: dco_decode_f_64(arr[5]),
      temperature: dco_decode_f_64(arr[6]),
      tint: dco_decode_f_64(arr[7]),
      vibrance: dco_decode_f_64(arr[8]),
      saturation: dco_decode_f_64(arr[9]),
      clarity: dco_decode_f_64(arr[10]),
      texture: dco_decode_f_64(arr[11]),
      dehaze: dco_decode_f_64(arr[12]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HistogramResult dco_decode_histogram_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return HistogramResult(
      red: dco_decode_list_prim_i_32_strict(arr[0]),
      green: dco_decode_list_prim_i_32_strict(arr[1]),
      blue: dco_decode_list_prim_i_32_strict(arr[2]),
      luminance: dco_decode_list_prim_i_32_strict(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  RawMetadataResponse dco_decode_raw_metadata_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return RawMetadataResponse(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
      format: dco_decode_String(arr[2]),
      cameraMake: dco_decode_opt_String(arr[3]),
      cameraModel: dco_decode_opt_String(arr[4]),
      lens: dco_decode_opt_String(arr[5]),
      iso: dco_decode_opt_box_autoadd_i_32(arr[6]),
      aperture: dco_decode_opt_box_autoadd_f_64(arr[7]),
      shutterSpeed: dco_decode_opt_String(arr[8]),
      focalLength: dco_decode_opt_box_autoadd_f_64(arr[9]),
      captureDate: dco_decode_opt_String(arr[10]),
      orientation: dco_decode_opt_box_autoadd_i_32(arr[11]),
      bitDepth: dco_decode_opt_box_autoadd_i_32(arr[12]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DecodedImageWrapper
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  DecodedImageWrapper
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  DecodedImageWrapper
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  DecodedImageWrapper
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DecodedImageWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EditParams sse_decode_box_autoadd_edit_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_edit_params(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  DecodedImage sse_decode_decoded_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return DecodedImage(width: var_width, height: var_height, data: var_data);
  }

  @protected
  EditParams sse_decode_edit_params(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_exposure = sse_decode_f_64(deserializer);
    var var_contrast = sse_decode_f_64(deserializer);
    var var_highlights = sse_decode_f_64(deserializer);
    var var_shadows = sse_decode_f_64(deserializer);
    var var_whites = sse_decode_f_64(deserializer);
    var var_blacks = sse_decode_f_64(deserializer);
    var var_temperature = sse_decode_f_64(deserializer);
    var var_tint = sse_decode_f_64(deserializer);
    var var_vibrance = sse_decode_f_64(deserializer);
    var var_saturation = sse_decode_f_64(deserializer);
    var var_clarity = sse_decode_f_64(deserializer);
    var var_texture = sse_decode_f_64(deserializer);
    var var_dehaze = sse_decode_f_64(deserializer);
    return EditParams(
        exposure: var_exposure,
        contrast: var_contrast,
        highlights: var_highlights,
        shadows: var_shadows,
        whites: var_whites,
        blacks: var_blacks,
        temperature: var_temperature,
        tint: var_tint,
        vibrance: var_vibrance,
        saturation: var_saturation,
        clarity: var_clarity,
        texture: var_texture,
        dehaze: var_dehaze);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HistogramResult sse_decode_histogram_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_red = sse_decode_list_prim_i_32_strict(deserializer);
    var var_green = sse_decode_list_prim_i_32_strict(deserializer);
    var var_blue = sse_decode_list_prim_i_32_strict(deserializer);
    var var_luminance = sse_decode_list_prim_i_32_strict(deserializer);
    return HistogramResult(
        red: var_red,
        green: var_green,
        blue: var_blue,
        luminance: var_luminance);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RawMetadataResponse sse_decode_raw_metadata_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_cameraMake = sse_decode_opt_String(deserializer);
    var var_cameraModel = sse_decode_opt_String(deserializer);
    var var_lens = sse_decode_opt_String(deserializer);
    var var_iso = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_aperture = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_shutterSpeed = sse_decode_opt_String(deserializer);
    var var_focalLength = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_captureDate = sse_decode_opt_String(deserializer);
    var var_orientation = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_bitDepth = sse_decode_opt_box_autoadd_i_32(deserializer);
    return RawMetadataResponse(
        width: var_width,
        height: var_height,
        format: var_format,
        cameraMake: var_cameraMake,
        cameraModel: var_cameraModel,
        lens: var_lens,
        iso: var_iso,
        aperture: var_aperture,
        shutterSpeed: var_shutterSpeed,
        focalLength: var_focalLength,
        captureDate: var_captureDate,
        orientation: var_orientation,
        bitDepth: var_bitDepth);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          DecodedImageWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DecodedImageWrapperImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          DecodedImageWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DecodedImageWrapperImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          DecodedImageWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DecodedImageWrapperImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDecodedImageWrapper(
          DecodedImageWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DecodedImageWrapperImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_edit_params(
      EditParams self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_edit_params(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_decoded_image(DecodedImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_edit_params(EditParams self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.exposure, serializer);
    sse_encode_f_64(self.contrast, serializer);
    sse_encode_f_64(self.highlights, serializer);
    sse_encode_f_64(self.shadows, serializer);
    sse_encode_f_64(self.whites, serializer);
    sse_encode_f_64(self.blacks, serializer);
    sse_encode_f_64(self.temperature, serializer);
    sse_encode_f_64(self.tint, serializer);
    sse_encode_f_64(self.vibrance, serializer);
    sse_encode_f_64(self.saturation, serializer);
    sse_encode_f_64(self.clarity, serializer);
    sse_encode_f_64(self.texture, serializer);
    sse_encode_f_64(self.dehaze, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_histogram_result(
      HistogramResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_i_32_strict(self.red, serializer);
    sse_encode_list_prim_i_32_strict(self.green, serializer);
    sse_encode_list_prim_i_32_strict(self.blue, serializer);
    sse_encode_list_prim_i_32_strict(self.luminance, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
      Int32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_raw_metadata_response(
      RawMetadataResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_String(self.cameraMake, serializer);
    sse_encode_opt_String(self.cameraModel, serializer);
    sse_encode_opt_String(self.lens, serializer);
    sse_encode_opt_box_autoadd_i_32(self.iso, serializer);
    sse_encode_opt_box_autoadd_f_64(self.aperture, serializer);
    sse_encode_opt_String(self.shutterSpeed, serializer);
    sse_encode_opt_box_autoadd_f_64(self.focalLength, serializer);
    sse_encode_opt_String(self.captureDate, serializer);
    sse_encode_opt_box_autoadd_i_32(self.orientation, serializer);
    sse_encode_opt_box_autoadd_i_32(self.bitDepth, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class DecodedImageWrapperImpl extends RustOpaque
    implements DecodedImageWrapper {
  // Not to be used by end users
  DecodedImageWrapperImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DecodedImageWrapperImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_DecodedImageWrapper,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_DecodedImageWrapper,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_DecodedImageWrapperPtr,
  );

  DecodedImage get inner => RustLib.instance.api
          .crateApiPhotoDecodingDecodedImageWrapperAutoAccessorGetInner(
        that: this,
      );

  set inner(DecodedImage inner) => RustLib.instance.api
      .crateApiPhotoDecodingDecodedImageWrapperAutoAccessorSetInner(
          that: this, inner: inner);

  Future<Uint8List> data() =>
      RustLib.instance.api.crateApiPhotoDecodingDecodedImageWrapperData(
        that: this,
      );

  Future<int> height() =>
      RustLib.instance.api.crateApiPhotoDecodingDecodedImageWrapperHeight(
        that: this,
      );

  Future<int> width() =>
      RustLib.instance.api.crateApiPhotoDecodingDecodedImageWrapperWidth(
        that: this,
      );
}
