-- Migration to support Master Spec Admin Upload
-- Generated by Trae

-- 1. Update Galleries Table
ALTER TABLE public.galleries 
ADD COLUMN IF NOT EXISTS watermark_enabled boolean NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'locked' CHECK (status IN ('locked', 'unlocked', 'archived')),
ADD COLUMN IF NOT EXISTS event_type text; -- Maps to shoot_type but keeping both for now or migrating data

-- If shoot_type exists, we can migrate it to event_type
UPDATE public.galleries SET event_type = shoot_type WHERE event_type IS NULL;

-- 2. Update Photos Table (Enhancement for Master Spec)
-- Spec wants specific URLs, but we use storage paths.
-- We can add helper columns or computed columns if needed, but the current schema is robust.
-- We will add 'is_favorite' for the client side features later.
ALTER TABLE public.photos
ADD COLUMN IF NOT EXISTS is_favorite boolean DEFAULT false;

-- 3. Notifications Table
-- Ensure 'type' can handle 'gallery_uploaded'
ALTER TABLE public.notifications
DROP CONSTRAINT IF EXISTS notifications_type_check;
-- (Re-adding constraint if needed, or leaving text open for flexibility)

-- 4. Storage Bucket Policies (SQL representation)
-- Ensure buckets exist (This is usually done in Supabase Dashboard or via API, but we can try via SQL extensions if available)
-- insert into storage.buckets (id, name) values ('galleries', 'galleries') on conflict do nothing;
